spring:
  application:
    name: point-of-sale
  modulith:
    detection-strategy: explicitly-annotated

  datasource:
    url: jdbc:postgresql://localhost:5432/db_pos
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:kritikpal123@gmail.com}
    password: ${MAIL_PASSWORD:fqzh mhov ldck lyxm}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

app:
  gpt-api-key: ${GPT_API_KEY:}
  email:
    login-url: ${APP_EMAIL_LOGIN_URL:http://localhost:3000/login}
    password-reset-url: ${APP_EMAIL_PASSWORD_RESET_URL:http://localhost:8080/reset-password}
    from-name: ${APP_EMAIL_FROM_NAME:POS Support}
  jwt:
    secret: ${JWT_SECRET:change-this-secret-key-to-at-least-32-characters}
    issuer: pos-backend
    access-seconds: 900    # 15 min
    refresh-seconds: 604800 # 7 days
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173,http://127.0.0.1:3000,http://127.0.0.1:5173}
  superadmin:
    email: yourgmail@gmail.com
    password: Your@123


springdoc:
  swagger-ui:
    path: /docs
    operations-sorter: alpha
    tags-sorter: alpha
    doc-expansion: none
    display-request-duration: true
    try-it-out-enabled: true
    filter: true
    deep-linking: true
    default-models-expand-depth: -1
    syntax-highlight:
      activated: true
      theme: obsidian

server:
  port: 8082

# spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL
