
spring:
    application:
        name: point-of-sale
    datasource:
        url: jdbc:postgresql://localhost:5432/db_pos
        username: postgres
        password: root
        driver-class-name: org.postgresql.Driver
    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false

app:
    jwt:
        secret: ${JWT_SECRET:mysupersecret}   # should come from ENV
        issuer: pos-backend
        access-seconds: 900    # 15 min
        refresh-seconds: 604800 # 7 days

    superadmin:
        email: yourgmail@gmail.com
        password: Your@123
#Warning
#spring.jpa.properties.jakarta.persistence.sharedCache.mode=ALL

springdoc:
    swagger-ui:
        path: /swagger-ui.html
server:
    port: 8082
